version: '3'
services:
  netapp:
    image: 'quay-ocp.unit.vn/menvs/netdapr:latest'
    ports:
      - '50001:50001'
      - '8082:8082'
    environment:
      - ASPNETCORE_HTTP_PORTS=8082
    depends_on:
      - placement
    networks:
      - hello-dapr
  netapp-dapr:
    image: "daprio/daprd:1.12.5"
    command: [
      "./daprd",
     "--app-id", "netapp",
     "--app-port", "3000",
     "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
     "--resources-path", "./components"
     ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - netapp
    network_mode: "service:netapp" # Attach the nodeapp-dapr service to the nodeapp network namespace

  placement:
    image: "docker.io/daprio/dapr:1.12.5"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
networks:
  hello-dapr: null